const fs = require('node:fs/promises');
const path = require('node:path');
const { build } = require('esbuild');

async function generateStaticPortfolio() {
  const root = path.resolve(__dirname, '..');
  const bundlePath = path.join(root, 'node_modules/.cache/static-portfolio/render.cjs');
  await build({
    stdin: {
      contents: `import React from 'react';
        import { renderToStaticMarkup } from 'react-dom/server';
        import App from './src/App';
        export default renderToStaticMarkup(<App staticMode />);`,
      resolveDir: root,
      loader: 'jsx',
    },
    outfile: bundlePath,
    bundle: true,
    platform: 'node',
    format: 'cjs',
    packages: 'external',
    loader: { '.js': 'jsx' },
    minify: true,
    logLevel: 'warning',
  });

  const html = require(bundlePath).default;
  const templatePath = path.join(root, 'public/index.html');
  const template = await fs.readFile(templatePath, 'utf8');
  const startMarker = '<!-- static-portfolio:start -->';
  const endMarker = '<!-- static-portfolio:end -->';
  const start = template.indexOf(startMarker);
  const end = template.indexOf(endMarker);
  if (start < 0 || end < start || template.indexOf(startMarker, start + 1) !== -1 || template.indexOf(endMarker, end + 1) !== -1) {
    throw new Error('Expected exactly one static portfolio placeholder in public/index.html.');
  }

  // Keep the fallback generated from the live components, not a second copy of the content.
  const generated = `${startMarker}\n    <!-- Generated by npm run generate:static. Do not edit this block. -->\n    <noscript>${html}</noscript>\n    `;
  await fs.copyFile(bundlePath.replace(/\.cjs$/, '.css'), path.join(root, 'public/static-portfolio.css'));
  await fs.writeFile(templatePath, template.slice(0, start) + generated + template.slice(end));
  console.log('Generated the no-JavaScript portfolio and stylesheet.');
}

generateStaticPortfolio().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
